apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qilsfpgjg-java-springboot
  janus-idp.io/tekton: qilsfpgjg-java-springboot
  backstage.io/kubernetes-id: qilsfpgjg-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qilsfpgjg-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
